app/urls.py
from django.contrib import admin
import django.contrib
import django.contrib.auth
import django.contrib.auth.urls
from django.urls import path, include
import django
from django.conf.urls import include
from django.contrib import admin


urlpatterns = [
    path('asffggtir/', admin.site.urls, name='admin'),
    path('', include('login.urls', namespace='users')),
    path('master/', include('master.urls'), name='master'),
    path('worker/', include('worker.urls'), name='worker'),
    path('analytics/', include('analytics.urls'), name='analytics'),    
]

login/urls.py
from django.contrib import admin
import django.contrib
import django.contrib.auth
import django.contrib.auth.urls
from django.urls import path, include
import django
from django.conf.urls import include
from django.contrib import admin
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'users'

urlpatterns = [    
    path('login/', views.LoginUser.as_view(redirect_authenticated_user=True), name='login'),
    path('', views.LoginUser.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', views.logout_user, name='logout'),    
]
 

master/urls.py
from django.contrib import admin
import django.contrib
import django.contrib.auth
import django.contrib.auth.urls
from django.urls import path, include
import django
from django.conf.urls import include
from django.contrib import admin
from . import views


urlpatterns = [    
    path('', views.master_home, name='master'),
    path('start_task/', views.start_task, name='start_task'),
    path('pause_task/<int:id_task>', views.pause_task, name='pause_task'),
    path('new_task/', views.new_task, name='new_task'),
    path('delete_task/', views.delete_task, name='new_task'),
    path('edit_task/', views.edit_task, name='edit_task'),
    path('hide_task/', views.hide_task, name='edit_task'),
    path('new_report/', views.new_report, name='new_report'),  
]

worker/urls.py
from django.contrib import admin
import django.contrib
import django.contrib.auth
import django.contrib.auth.urls
from django.urls import path, include
import django
from django.conf.urls import include
from django.contrib import admin
from . import views


urlpatterns = [
    
    path('', views.worker_home, name='worker'),
    path('start_working/', views.start_working, name='start_working'),
    path('month/start_working/', views.start_working, name='month_start_working'),
    path('week/start_working/', views.start_working, name='week_start_working'),
    path('now/start_working/', views.start_working, name='now_start_working'),
    path('now/', views.task_now, name='now_filter'),
    path('week/', views.task_week, name='week_filter'),
    path('month/', views.task_month, name='month_filter'),
    path('pause_task/', views.pause_task, name='pause_working'),
    path('deny_task/', views.deny_task, name='deny_working'),
    path('complete_task/', views.complete_task, name='complete_working'),
    path('setting-up/', views.start_settingUp, name='settingUp'),
    path('edit-profile-amount-value/', views.edit_profile_amount, name='change_profile_amount'),
    path('shiftChange/', views.shiftChange, name='change_worker'),
        
]

login/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import HStoreField
from django.db import models
from master import models as master_models

class User(AbstractUser):
  position = models.CharField(max_length=100, verbose_name='Должность')
  production_area_id = models.ForeignKey(master_models.Workplace,  null=True, on_delete=models.SET_NULL)
  production_area = models.CharField(max_length=100, verbose_name='Производственный участок')
  access_page = models.CharField(max_length=100, verbose_name='Перечень страниц для доступа')
  
  

worker/models.py
from django.db import models
from login import models as login_model
from django.contrib.postgres.fields import HStoreField

class WorkerTypeProblem(models.Model):
  name_problem = models.CharField('Наименование типа проблемы', max_length=100)
  
  def __str__(self):
    return str(self.name_problem) 
class Users_analytics(models.Model):
  userId =  models.ForeignKey(login_model.User, null=True, on_delete=models.SET_NULL)
  settingUp = HStoreField('Количество времени на переналадку', null=True)
  profile_amount = HStoreField('Количество изготовленного профиля по датам', null=True)
  work_time = HStoreField('Время полезной работы', null=True)
  
  def __str__(self):
    return self.userId

login/forms.py
from .models import *
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import DateTimeInput, TextInput, Select
from django.contrib.auth import get_user_model

  
class LoginForm(AuthenticationForm):
    username = forms.CharField(label='ID пользователя', max_length=150, widget=forms.TextInput(attrs={'class': 'textbox__item textbox-id', 'placeholder': 'Введите ID пользователя'}))
    password = forms.CharField(label='Пароль', max_length=150, widget=forms.PasswordInput(attrs={'class': 'textbox__item', 'placeholder': 'Введите пароль'}))
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

worker/forms.py
from master.models import *
from .models import WorkerTypeProblem
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import DateTimeInput, TextInput, Select

class PauseTaskForm(forms.Form):
    problem_type = forms.ModelChoiceField(queryset=WorkerTypeProblem.objects.all(), widget=Select(attrs={"class":"pause_task_popup__cat-problem"}))
    problem_comments = forms.CharField(widget=forms.Textarea(attrs={"class":"pause_task_popup__comment", 'style':'resize:none;'}))
    
class DenyTaskForm(forms.Form):
    problem_type = forms.ModelChoiceField(queryset=WorkerTypeProblem.objects.all(), widget=Select(attrs={"class":"pause_task_popup__cat-problem"}))
    problem_comments = forms.CharField(widget=forms.Textarea(attrs={"class":"pause_task_popup__comment", 'style':'resize:none;'}))

login/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy, reverse
from .forms import LoginForm
from .utils import DataMixin
from django.contrib.auth import authenticate, login, logout


class LoginUser(LoginView):
  form_class = LoginForm
  template_name = 'login.html'
  extra_context = {'title': 'Авторизация'}
    
  
  def get_success_url(self):    
    if self.request.user.is_superuser:
      # print('Перенаправляем на admin-панель')
      return reverse_lazy('admin:index')
    elif 'master.view_tasks' in self.request.user.get_group_permissions():      
      # print('Перенаправляем на master')
      return reverse_lazy('master')
    elif 'worker.change_workertypeproblem' in self.request.user.get_group_permissions():      
      # print('Перенаправляем на worker')
      return reverse_lazy('worker')    
 

def logout_user(request):
  logout(request)
  return HttpResponseRedirect(reverse('users:login'))

  
  

        

master/views.py
from django.shortcuts import render
from .models import Tasks
from .forms import NewTaskForm, EditTaskForm, PauseTaskForm, ReportForm
from .databaseWork import DatabaseWork
from django.http import HttpResponse, JsonResponse, FileResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import UpdateView
from django.urls import reverse_lazy
from .report import create_excel_from_dict_list
import math, datetime, os





@login_required
@permission_required(perm='master.view_tasks', raise_exception=True)
def master_home(request):
  new_task_form = NewTaskForm()
  edit_task_form = EditTaskForm()
  new_paused_form = PauseTaskForm()
  report_form = ReportForm()
  tasks = Tasks.objects.all().filter(task_is_vision=True).order_by('-id')    
  tasks_stat_all = Tasks.objects.all().count()
  tasks_stat_complited = Tasks.objects.filter(task_status=2).count()  
  load_data = {'title': 'AT-Manager', "task_stat": f'{tasks_stat_all}/{tasks_stat_complited}'}
  # print(request.META)
  
  return render(request, 'master.html', {'load_data': load_data, 'new_task_form':new_task_form,
                                         'edit_task_form': edit_task_form, 'new_paused_form':new_paused_form,
                                         'tasks': tasks, 'report_form': report_form})

@login_required()
@permission_required(perm='master.change_tasks', raise_exception=True)
def start_task(request):    
  if request.method == 'GET':
    data_task = DatabaseWork({'id_task':request.GET.get('id_task')})
    user_name = f'{request.user.last_name} {request.user.first_name}'
    user_position =f'{request.user.position}'
    task = data_task.push_to_workers(user_name, user_position)     
    if task == True:      
      return HttpResponse('Статус задачи успешно обновлен')
    else:
      return HttpResponse(f'Ошибка обновления задачи: {task}')
  else:
    return HttpResponse('Только GET-запрос')

# Приостановка выполнения задания 
@login_required 
@permission_required(perm='master.change_tasks', raise_exception=True)
def pause_task(request, id_task):   
  if request.method == 'POST':    
    new_paused_form = PauseTaskForm(request.POST)    
    if new_paused_form.is_valid():      
      user_name = f'{request.user.last_name} {request.user.first_name}'
      user_position =f'{request.user.position}'
      new_data_file = DatabaseWork(new_paused_form.cleaned_data)                   
      new_task_file = new_data_file.paused_task(user_name, user_position, id_task)        
      if  new_task_file == True:
        # print(f'Добавление прошло успешно, id записи: {new_data_file.new_task_id}')
        return redirect('/master', permanent=True)
      else:
        return HttpResponse(f'Ошибка: {new_task_file}')
   
# Добавление новой задачи
@login_required
@permission_required(perm='master.add_tasks', raise_exception=True)
def new_task(request):
  if request.method == 'POST':    
    new_task_form = NewTaskForm(request.POST)    
    if new_task_form.is_valid():      
      user_name = f'{request.user.last_name} {request.user.first_name}'
      user_position =f'{request.user.position}'
      new_data_file = DatabaseWork(new_task_form.cleaned_data)
      new_history_file = new_data_file.add_new_history_data(user_name, user_position, new_task_form.cleaned_data['task_comments'])            
      if new_history_file == True:        
        new_task_file = new_data_file.add_new_task_data(user_name)        
        if  new_task_file == True:
          # print(f'Добавление прошло успешно, id записи: {new_data_file.new_task_id}')
          return redirect('/master', permanent=True)
        else:
          return HttpResponse(f'Ошибка: {new_task_file}')
      else:        
        return HttpResponse(f'Ошибка: {new_history_file}')   

# Удаление задачи    
@login_required
@permission_required(perm='master.change_tasks', raise_exception=True)  
def delete_task(request):
  if request.method == 'GET':
    data_task = DatabaseWork({'id_task':request.GET.get('id_task')})
    task = data_task.delete_task()     
    if task == True:      
      return HttpResponse('Задача удалена')
    else:
      return HttpResponse(f'Ошибка удаления задачи: {task}') 

# Изменение задачи  
@login_required
@permission_required(perm='master.change_tasks', raise_exception=True)  
def edit_task(request):
  global id_task  
  if request.method == 'GET':
      id_task = request.GET.get('id_task')
      data_task = DatabaseWork({'id_task':request.GET.get('id_task')})
      data = data_task.get_data_from_tasks()      
      return JsonResponse({'task_name': data.task_name, 'task_timedate_start':data.task_timedate_start,
                          'task_timedate_end': data.task_timedate_end, 'task_profile_type': data.task_profile_type_id, 
                          'task_workplace': data.task_workplace_id, 'task_profile_amount': data.task_profile_amount,
                          'task_comments': data.task_comments})
  elif request.method == 'POST':    
    edit_task_form = EditTaskForm(request.POST)    
    if edit_task_form.is_valid():      
      user_name = f'{request.user.last_name} {request.user.first_name}'
      user_position =f'{request.user.position}'
      new_data_file = DatabaseWork(edit_task_form.cleaned_data)
      #new_history_file = new_data_file.add_new_history_data(user_name, user_position)       
      new_task_file = new_data_file.edit_data_from_task(user_name, user_position, id_task)        
      if  new_task_file == True:
        # print(f'Добавление прошло успешно, id записи: {new_data_file.new_task_id}')
        return redirect('/master', permanent=True)
      else:
        return HttpResponse(f'Ошибка: {new_task_file}')
      
  else:
    new_task_form = EditTaskForm() 
    
@login_required
@permission_required(perm='master.change_tasks', raise_exception=True)  
def hide_task(request):
  if request.method == 'GET':
    data_task = DatabaseWork({'id_task':request.GET.get('id_task')})
    task = data_task.hide_task()     
    if task == True:      
      return HttpResponse('Задача скрыта')
    else:
      return HttpResponse(f'Ошибка скрытия задачи: {task}')
  else:
    return HttpResponse('Только GET-запрос')


@login_required
@permission_required(perm='master.change_tasks', raise_exception=True)
def new_report(request):
  if request.method == 'POST':
    report_form = ReportForm(request.POST)
    if report_form.is_valid():
      data = report_form.cleaned_data
      start_date = data['date_start']
      end_date = data['date_end']
      tasks = Tasks.objects.all().filter(task_timedate_end_fact__range=(start_date, end_date))
      dict_list = []
      for task in tasks:
        profile_index = 0
        my_str = task.worker_accepted_task
        arr_str = my_str.split(', ')
        for value in arr_str:
          start_i = value.find('(')
          end_i = value.find(')')         
          int_data = int(value[start_i + 1:end_i])
          profile_index = profile_index + int_data
          total_length = round(float(task.task_profile_length) * int(int_data), 2) 
          total_time = dates_to_time(task.task_timedate_start_fact, task.task_timedate_end_fact)         
          new_row = {'Ф.И.О': value[0:start_i], 'Номер линии': task.task_workplace_id, 'Марка изделия': task.task_profile_type.profile_name, 'Общее кол-во п/м': total_length,
                                                        'Отработанные часы':total_time, 'Ср. ед.':'0', 'Хоз. работы':'Да', 'Подпись работника':''}
          dict_list.append(new_row)
        
      answer = create_excel_from_dict_list(dict_list, f'Акт от {datetime.date.today()}.xlsx')
      link = f'/app/{answer}'
      link = link.replace('\\', '/')      
      return FileResponse(open(os.path.join(answer), "rb"))
    else:
      return redirect('/master', permanent=True)
  
  else:
    return HttpResponse('Только GET-запрос')  


def dates_to_time(date1, date2):
  hourse_string = '0'
  minutes_string = '0'
  seconds_string = '0'
  result_time = date2 - date1  
  sum_difference = math.modf(result_time.total_seconds() / 60 / 60)
  hours = int(sum_difference[1])
  if abs(hours)  < 10:
    if hours < 0:
      hourse_string = f'-0{abs(hours)}'
    else:
      hourse_string = f'0{hours}'
  else:
      hourse_string = f'{hours}'  
  
     
       
  minutes_sum = math.modf(sum_difference[0] * 60)
  minutes = abs(int(minutes_sum[1]))
  if minutes  < 10:
    minutes_string = f'0{minutes}'
  else:
    minutes_string = f'{minutes}'    
  seconds = abs(int(minutes_sum[0] * 60) )   
  if seconds  < 10:
    seconds_string = f'0{seconds}'
  else:
    seconds_string = f'{seconds}'     
    
  return f'{hourse_string}:{minutes_string}:{seconds_string}'

app/templates/analitycs.html
<!DOCTYPE html>
{% load static %}
{% load split_tag %}
{% if user.is_authenticated %}
<html lang="ru">
<head>  
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static "css/normalize.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">  
  <link rel="stylesheet" href="{% static "css/analytics.css" %}">
  <title>AT-Manager (Аналитика)</title>
</head>
<body>
<header class="header">
  <div class="wrapper">
    <div class="header-content">
      <div class="header__lef-side">
        <div class="header-logo">
          <span class="logo-title">AT-Manager <br>Analitics</span>
        </div>       
      </div>     
      <div class="header__right__side">
        <div class="person-info">
          <span class="person-info__name">{{ user.last_name }} {{ user.first_name }}</span>
          <span class="person-info__department">{{user.position}}</span>
          <span class="person-info__department">{{user.production_area}}</span>
        </div>
        <div class="logout">
          <a href="{% url 'users:logout' %}" class="logout-link">Выход</a>
        </div>
      </div>           
    </div>   
  </div>
</header>
<section class="main">
  <div class="wrapper">    
    <div class="current-work__wrapper">
      <div class="current-work__title">
        <h2>Текущая работа</h2>
      </div>      
      <div class="current-work">
        <div class="current-work__profile">
          <select name="choices">
            <option value="1">По рабочим</option>
            <option value="2">По видам профиля</option>
            <option value="3">По рабочим местам</option>
          </select>
          <canvas id="chart-current-work__profile"></canvas>
        </div>
        <div class="current-work__loading-equipment">
          <div class="loading-equipment__item">
            <img class="loading-equipment-icon" src="{% static "img/device-electronic-machine.svg" %}" alt="machine-icon">
            <div class="loading-equipment__status-bar"></div>
            <div class="loading-equipment__task-status-block">
              <div class="task-status-block__now">
                <h3>Текущее задание:</h3>
                <span>Задание 1,  Т-профиль, требуется: 100 шт, текущее количество: 80 шт. </span>
              </div>
              <div class="task-status-block__future">
                <h3>Поток заданий:</h3>
                <div class="block__future__item">                
                  <span>Задание 2,  Т-профиль, требуется: 200 шт</span>
                </div>
                <div class="block__future__item">                
                  <span>Задание 3,  Т-профиль, требуется: 50 шт</span>
                </div>             
              </div>
            </div>
          </div>
          <div class="loading-equipment__item">
            <img class="loading-equipment-icon" src="{% static "img/device-electronic-machine.svg" %}" alt="machine-icon">
            <div class="loading-equipment__status-bar"></div>
            <div class="loading-equipment__task-status-block">
              <div class="task-status-block__now">
                <h3>Текущее задание:</h3>
                <span>Задание 1,  Т-профиль, требуется: 100 шт, текущее количество: 80 шт. </span>
              </div>
              <div class="task-status-block__future">
                <h3>Поток заданий:</h3>
                <div class="block__future__item">                
                  <span>Задание 2,  Т-профиль, требуется: 200 шт</span>
                </div>
                <div class="block__future__item">                
                  <span>Задание 3,  Т-профиль, требуется: 50 шт</span>
                </div>             
              </div>
            </div>
          </div>
          <div class="loading-equipment__item">
            <img class="loading-equipment-icon" src="{% static "img/device-electronic-machine.svg" %}" alt="machine-icon">
            <div class="loading-equipment__status-bar"></div>
            <div class="loading-equipment__task-status-block">
              <div class="task-status-block__now">
                <h3>Текущее задание:</h3>
                <span>Задание 1,  Т-профиль, требуется: 100 шт, текущее количество: 80 шт. </span>
              </div>
              <div class="task-status-block__future">
                <h3>Поток заданий:</h3>
                <div class="block__future__item">                
                  <span>Задание 2,  Т-профиль, требуется: 200 шт</span>
                </div>
                <div class="block__future__item">                
                  <span>Задание 3,  Т-профиль, требуется: 50 шт</span>
                </div>             
              </div>
            </div>
          </div>
          <div class="loading-equipment__item">
            <img class="loading-equipment-icon" src="{% static "img/device-electronic-machine.svg" %}" alt="machine-icon">
            <div class="loading-equipment__status-bar"></div>
            <div class="loading-equipment__task-status-block">
              <div class="task-status-block__now">
                <h3>Текущее задание:</h3>
                <span>Задание 1,  Т-профиль, требуется: 100 шт, текущее количество: 80 шт. </span>
              </div>
              <div class="task-status-block__future">
                <h3>Поток заданий:</h3>
                <div class="block__future__item">                
                  <span>Задание 2,  Т-профиль, требуется: 200 шт</span>
                </div>
                <div class="block__future__item">                
                  <span>Задание 3,  Т-профиль, требуется: 50 шт</span>
                </div>             
              </div>
            </div>
          </div>
        </div>
      </div>      
      
    </div>
    <div class="planned-work_wrapper">
      <div class="planned-work__title">
        <h2>Плановая работа</h2>
      </div>
      <div class="planned-work">
        <div class="planned-work__performance">            
          <canvas id="chart-planned-work__performance"></canvas>
        </div>
        <div class="planned-work__load">            
          <canvas id="chart-planned-work__load"></canvas>
        </div>          
      </div>            
    </div>
    <div class="analysis-of-workers__wrapper">
      <div class="analysis-of-workers__title">
        <h2>Рабочая загрузка</h2>
      </div>
      <select name="analysis-of-workers__filter__date">
        <option value="1">Сегодня</option>
        <option value="2">Последние 7 дней</option>
        <option value="3">Последний месяц</option>
        <option value="4">Пол года</option>
        <option value="5">Последний год</option>        
        <option value="6">За все время</option>
      </select>
      <div class="analysis-of-workers">
        <div class="setup-speed__wrapper">
          <canvas id="chart__setup-speed"></canvas> 
        </div>
        <div class="profile-amount__wrapper">
          <canvas id="chart__profile-amount"></canvas> 
        </div>
        <div class="hours-worked__wrapper">
          <canvas id="chart__hours-worked"></canvas> 
        </div>
        <div class="effectiveness__wrapper">
          <canvas id="chart__effectiveness"></canvas> 
        </div>
      </div>
    </div>
  </div>
</section>
<footer class="footer">
  <div class="wrapper">
    <div class="footer-content">     
    </div>
  </div>
</footer>
<script src="{% static "js/jquery/jquery-3.7.1.min.js" %}"></script>
<script src="{% static "js/chart/chart.js" %}"></script> 
<script src="{% static "js/analitics.js" %}"></script>   
</body>
</html>
{% endif %}

app/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static "css/normalize.css" %}">
  <link rel="stylesheet" href="{% static "css/style.css" %}">  
  <link rel="stylesheet" href="{% static "css/lg-style.css" %}"> 
  <link rel="stylesheet" href="{% static "css/media-login.css" %}"> 
  <title>AT-Manager</title>
</head>
<body>
<header class="header"></header>
<section class="content">
  <div class="content__wrapper">
    <div class="content__inner-block">
      <div class="left-side">
        <div class="left-side__wrapper">
          <div class="title">
            <div class="title__program-name">
              <h1 class="program-name__text">AT-Manager</h1>
            </div>
            <div class="title__quote">
              <h3 class="quote__text">Цифровая трансформация - это фундоментальная реальность для бизнеса сегодня</h3>
            </div>
          </div>
          <div class="logo">
            <img src="{% static "/img/logo.png" %}" alt="Логотип компании Альтернатива">  
          </div>  
        </div>
      </div>
      <div class="right-side">
        <form class="right-side__wrapper" method="post">           
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}" />             
          <div class="welcome-text">
            <div class="welcome-text__title">
              <h2 class="title__text">Добро пожаловать!</h2>
            </div>
            <div class="welcome-text__sub-title">
              <span class="sub-title__text">Начать работу</span>              
            </div>        
          </div>
          <div class="textbox-list">
            <div class="textbox-id">              
              {{ form.username }}              
            </div>
            
            <div class="textbox-password">              
              {{ form.password }}
            </div>
          </div>
          <div class="buttons-list"> 
            <button class="button__enter-app" type="submit">Вход</button>
            <button class="button__qr-code">Вход по QR-коду</button> 
            {{ form.non_field_errors.as_text }}
          </div>  
        </form>
      </div>
    </div>
  </div>  
</section>
<footer class="footer"></footer> 
<script src="{% static "/js/login.js" %}"></script> 
</body>
</html>